---   
- name: Настройка color bash для ias
  ansible.builtin.lineinfile:
    path: '/home/ias/.bashrc'
    line: 'export PS1="\[\e[1;33m\]\u@\h:\[\e[33m\]\w\[\e[33m\]\$ \[\e[m\]"'
    insertafter: EOF
